### ISSUE TITLE
Argument names are followed by colon not semi-colon before type

### ISSUE THREAD

**Issue by d-schmidt** [Zhuinden/guide-to-kotlin#1]
* we must specify argument list with the name of the argument first, **semi-**colon, then the type

should be 

* we must specify argument list with the name of the argument first, colon, then the type

**Comment by Zhuinden** [comment]
Aaaah English names I'll fix it thanks

**Comment by Zhuinden** [comment]
I'll proof check later to see if I ever referred to `:`s by name anywhere else, if I did I'm pretty sure the error is consistent. :disappointed:

Anyways, thanks for the notice!
