### ISSUE TITLE
Collections initializers

### ISSUE THREAD

**Issue by jmfayard** [Zhuinden/guide-to-kotlin#10]
Re: https://github.com/Zhuinden/guide-to-kotlin/wiki/1.)-Major-Syntax-Differences#arrayof-and-arrayofnulls-and-listof-and-mutablelistof-and-linkedmapof

There is a handy collection initializer that is not very well-known where you create a list with a size of elements and a lambda for each element

```kotlin
val squares = List(size = 6) { it * it } 
// same as:
val squares = listOf(0, 1, 4, 9, 16, 25)
```

**Comment by Zhuinden** [comment]
Added, thanks

**Comment by jmfayard** [comment]
@Zhuinden 
It was fun to review this first chapter and I could do that for the others when I have time. 
Is there a better way to contribute than via the issues?

**Comment by Zhuinden** [comment]
Technically I could be like Codepath and just untick this box:

> [X] Restrict editing to collaborators only 
> Public wikis will still be readable by everyone.

Or I could invite you to be a collaborator, which is what I did :+1:
