### ISSUE TITLE
Visibility modifiers: package visibility does exist

### ISSUE THREAD

**Issue by homer-jay** [Zhuinden/guide-to-kotlin#13]
In the [visibility section](https://github.com/Zhuinden/guide-to-kotlin/wiki/1.-Major-Syntax-Differences#visibility-in-kotlin-public-by-default-private-protected-internal), it says:

> There is NO package visibility in Kotlin

This is actually not true, as explained in the official guide, in the section [Visibility modifiers - package](https://kotlinlang.org/docs/reference/visibility-modifiers.html#packages).

I was also confused by the explanation about internal. In the wiki it says that internal is not equivalent to package, and it is true, but I'd add that internal is "module" visibility (where modules are IntelliJ modules, Maven projects, gradle source sets, etc).

**Comment by Zhuinden** [comment]
`internal` is compilation module visibility, which means it is completely different from `package` visibility.

Therefore, Kotlin has the addition of `internal` visibility, but does not have `package` visibility.

Also `internal` gets quirky name in Java.

**Comment by homer-jay** [comment]
> but does not have `package` visibility

OK, so strictly speaking it does not have Java's package-default visibility mechanism, but it allows for "top-level" members directly inside a package:

```
package foo

fun bar() { ... }
```

So I agree it's not the same as in Java, because in Kotlin `bar` would be accesible by any class in a different package (as long as you import it). But in some sense it fills that void, because top-level members can be used (without the need to import them) by classes in that same package. I thought Java programmers would probably appreciate reading about it.

**Comment by Zhuinden** [comment]
The problem isn't that you don't need to import it, it's that you can still import it elsewhere and see it.

The top-level declaration is essentially public. 😉

**Comment by homer-jay** [comment]
Ok then. That would be like `import static`. Closing.
