### ISSUE TITLE
Interface with val and vars

### ISSUE THREAD

**Issue by jmfayard** [Zhuinden/guide-to-kotlin#7]
Re: https://github.com/Zhuinden/guide-to-kotlin/wiki/1.)-Major-Syntax-Differences#interfaces-with-val-var-and-fun

I would add that you can define a default implementation in the interface

```kotlin
interface MyContract {
  var value: String
  val name: String
  val params: Map<String, String> 
     get() = emptyMap()

  fun doSomething(input1: String, input2: String) {
    // Default Implementation that does nothing
  }
}
```

Default implementations are great especially when you add an optional feature to an interface later. You don't break the existing implementations if you have a default implementaiton.

And that using properties instead of methods is such a great idea because you can use all the powerful encapsulation features that come with properties. 

Like defining the overriding properties in the constructor

```kotlin
class SimpleContract(override var value: String, override val name: String) 
  : MyContract 
```

**Comment by Zhuinden** [comment]
I actually have default implementations in a different section at https://github.com/Zhuinden/guide-to-kotlin/wiki/2.)-Basic-Kotlin-Features#interfaces-and-default-implementation

However I did miss `override val` for some reason and should definitely add that.

**edit:** added
