### ISSUE TITLE
Use-cases for objects

### ISSUE THREAD

**Issue by jmfayard** [Zhuinden/guide-to-kotlin#8]
Re: https://github.com/Zhuinden/guide-to-kotlin/wiki/1.)-Major-Syntax-Differences#object-for-singleton

Proposed good use cases for `object`:

1. Have an object where you define your constants:

```kotlin
object Network {
    const val API_URL = "http://httpbin.org"
    const val TIMEOUT = 1000 // ms
}
```

2. Use it as a namespace for pure functions

```kotlin
object Math {
    fun sum(a: Int, b: Int) : Int = a+b
    //.... 
}
```

**Comment by Zhuinden** [comment]
Makes sense, added with attribution :+1:
