### ISSUE TITLE
No ternary operators

### ISSUE THREAD

**Issue by jmfayard** [Zhuinden/guide-to-kotlin#9]
No ternary oeprator: I would add that the fact there is no ternary operator is just the logical conclusion of everything being an expression. Once you get that, using if/else or when just makes sense. 

https://github.com/Zhuinden/guide-to-kotlin/wiki/1.)-Major-Syntax-Differences#there-is-no-condition--true--false-ternary-operator

**Comment by Zhuinden** [comment]
done
